# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20170914_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
