# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_auto_20170914_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructors.Position'),
            preserve_default=False,
        ),
    ]
