# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_auto_20170914_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
