# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_auto_20170914_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(to='instructors.Course'),
        ),
    ]
